[application]
name = "widgets-dioxus"
default_platform = "web"
asset_dir = "public"

[web.app]
title = "ars-ui Dioxus Widgets"

[web.resource]
style = ["./ars-base.css", "./ars-interactions.css"]
script = []

[web.resource.dev]
style = ["./ars-base.css", "./ars-interactions.css"]
script = []
