[formatting]
align_comments       = true
align_entries        = true
array_auto_collapse  = true
array_trailing_comma = false
column_width         = 100
crlf                 = false
trailing_newline     = true
