//! Standalone keyboard interaction types for normalized custom key handling.
//!
//! This module provides the framework-agnostic keyboard event contract used by
//! components that need direct `keydown` and `keyup` handling without bundling
//! behavior such as press, focus, or movement semantics.

use std::string::String;

/// Re-export of the canonical named-key enum from `ars-core`.
///
/// [`KeyboardKey`] mirrors the W3C UI Events `KeyboardEvent` key Values (2025
/// Recommendation). `ars-core` owns the enum so interaction, accessibility,
/// and adapter crates all share the same normalized key model.
pub use ars_core::KeyboardKey;

/// Configuration for standalone keyboard event handling.
#[derive(Clone, Debug, Default)]
pub struct KeyboardConfig {
    /// Whether the keyboard interaction is disabled.
    pub disabled: bool,
}

/// Normalized keyboard event data.
///
/// Named `KeyboardEventData` instead of `KeyboardEvent` to avoid collisions
/// with framework or DOM event types such as `web_sys::KeyboardEvent`.
#[derive(Clone, Debug)]
pub struct KeyboardEventData {
    /// The named key, normalized from W3C `KeyboardEvent.key` values.
    ///
    /// Printable character keys use [`KeyboardKey::Unidentified`] and place the
    /// final character in [`Self::character`] instead.
    pub key: KeyboardKey,

    /// The printable character produced by this key press, if any.
    ///
    /// For example, `A` maps to `Some('a')` or `Some('A')`, `Space` maps to
    /// `Some(' ')`, and named control keys such as `Enter` map to `None`.
    pub character: Option<char>,

    /// The physical key code, such as `"KeyA"` or `"Digit1"`.
    ///
    /// This uses the browser `KeyboardEvent.code` contract rather than the
    /// localized `KeyboardEvent.key` value.
    pub code: String,

    /// Whether the Shift modifier was held.
    pub shift_key: bool,

    /// Whether the physical Ctrl key was held.
    ///
    /// This is the raw Ctrl state, not a platform-abstracted action modifier.
    /// Consumers that want Ctrl on Windows/Linux and Cmd on macOS should use
    /// the higher-level action-key abstractions provided elsewhere.
    pub ctrl_key: bool,

    /// Whether the Alt modifier was held.
    pub alt_key: bool,

    /// Whether the Meta modifier was held.
    pub meta_key: bool,

    /// Whether this event is an auto-repeat generated by holding the key down.
    pub repeat: bool,

    /// Whether this event fired during active IME composition.
    ///
    /// Components must suppress character-driven interactions while this is
    /// `true`, because the user is still composing a multi-keystroke character.
    pub is_composing: bool,
}

/// Keyboard events emitted by the standalone keyboard interaction.
///
/// Named `ArsKeyboardEvent` to avoid collisions with DOM and framework event
/// types while preserving a small, framework-agnostic enum surface. Adapters
/// converting from DOM events should use the full path `web_sys::KeyboardEvent`
/// for the DOM type and this type for the normalized event.
#[derive(Clone, Debug)]
pub enum ArsKeyboardEvent {
    /// A key was pressed down.
    KeyDown(KeyboardEventData),
    /// A key was released.
    KeyUp(KeyboardEventData),
}

#[cfg(test)]
mod tests {
    use super::{ArsKeyboardEvent, KeyboardConfig, KeyboardEventData, KeyboardKey};
    use crate::keyboard::KeyboardKey as ReexportedKeyboardKey;

    #[test]
    fn keyboard_config_default_disabled_false() {
        let config = KeyboardConfig::default();
        assert!(!config.disabled);
    }

    #[test]
    fn keyboard_event_data_constructs_with_all_fields() {
        let data = KeyboardEventData {
            key: KeyboardKey::ArrowRight,
            character: Some('x'),
            code: "KeyX".to_owned(),
            shift_key: true,
            ctrl_key: true,
            alt_key: false,
            meta_key: false,
            repeat: true,
            is_composing: false,
        };

        assert_eq!(data.key, KeyboardKey::ArrowRight);
        assert_eq!(data.character, Some('x'));
        assert_eq!(data.code, "KeyX");
        assert!(data.shift_key);
        assert!(data.ctrl_key);
        assert!(!data.alt_key);
        assert!(!data.meta_key);
        assert!(data.repeat);
        assert!(!data.is_composing);
    }

    #[test]
    fn ars_keyboard_event_keydown_and_keyup_match() {
        let data = KeyboardEventData {
            key: KeyboardKey::Enter,
            character: None,
            code: "Enter".to_owned(),
            shift_key: false,
            ctrl_key: false,
            alt_key: false,
            meta_key: false,
            repeat: false,
            is_composing: false,
        };

        match ArsKeyboardEvent::KeyDown(data.clone()) {
            ArsKeyboardEvent::KeyDown(inner) => {
                assert_eq!(inner.key, KeyboardKey::Enter);
                assert_eq!(inner.code, "Enter");
            }
            ArsKeyboardEvent::KeyUp(_) => panic!("expected KeyDown"),
        }

        match ArsKeyboardEvent::KeyUp(data) {
            ArsKeyboardEvent::KeyUp(inner) => {
                assert_eq!(inner.key, KeyboardKey::Enter);
                assert_eq!(inner.code, "Enter");
            }
            ArsKeyboardEvent::KeyDown(_) => panic!("expected KeyUp"),
        }
    }

    #[test]
    fn named_key_round_trips_through_keyboard_key() {
        let key = KeyboardKey::from_key_str("ArrowLeft");
        assert_eq!(key, KeyboardKey::ArrowLeft);
        assert_eq!(key.as_w3c_str(), "ArrowLeft");
    }

    #[test]
    fn printable_character_uses_unidentified_plus_character() {
        let data = KeyboardEventData {
            key: KeyboardKey::from_key_str("a"),
            character: Some('a'),
            code: "KeyA".to_owned(),
            shift_key: false,
            ctrl_key: false,
            alt_key: false,
            meta_key: false,
            repeat: false,
            is_composing: false,
        };

        assert_eq!(data.key, KeyboardKey::Unidentified);
        assert_eq!(data.character, Some('a'));
    }

    #[test]
    fn space_uses_keyboard_key_space_and_character_space() {
        let data = KeyboardEventData {
            key: KeyboardKey::from_key_str(" "),
            character: Some(' '),
            code: "Space".to_owned(),
            shift_key: false,
            ctrl_key: false,
            alt_key: false,
            meta_key: false,
            repeat: false,
            is_composing: false,
        };

        assert_eq!(data.key, KeyboardKey::Space);
        assert_eq!(data.character, Some(' '));
    }

    #[test]
    fn enter_uses_keyboard_key_enter_and_no_character() {
        let data = KeyboardEventData {
            key: KeyboardKey::from_key_str("Enter"),
            character: None,
            code: "Enter".to_owned(),
            shift_key: false,
            ctrl_key: false,
            alt_key: false,
            meta_key: false,
            repeat: false,
            is_composing: false,
        };

        assert_eq!(data.key, KeyboardKey::Enter);
        assert_eq!(data.character, None);
    }

    #[test]
    fn ime_composition_flag_is_preserved() {
        let data = KeyboardEventData {
            key: KeyboardKey::Process,
            character: None,
            code: "KeyA".to_owned(),
            shift_key: false,
            ctrl_key: false,
            alt_key: false,
            meta_key: false,
            repeat: false,
            is_composing: true,
        };

        assert!(data.is_composing);
    }

    #[test]
    fn repeat_flag_is_preserved() {
        let data = KeyboardEventData {
            key: KeyboardKey::ArrowDown,
            character: None,
            code: "ArrowDown".to_owned(),
            shift_key: false,
            ctrl_key: false,
            alt_key: false,
            meta_key: false,
            repeat: true,
            is_composing: false,
        };

        assert!(data.repeat);
    }

    #[test]
    fn keyboard_module_reexports_keyboard_key() {
        let key = ReexportedKeyboardKey::from_key_str("Enter");
        assert_eq!(key, KeyboardKey::Enter);
    }
}
