[alias]
xtask = "run --package xtask --"

xci       = "xtask ci"
xci-fast  = "xtask ci --profile fast"
xclippy   = "xtask clippy"
xcrap     = "xtask crap"
xcov      = "xtask cov"
xexamples = "xtask examples"
xfmt      = "run --quiet --package xtask -- fmt"
xmcp      = "xtask mcp"
xmutants  = "xtask mutants"
xspec     = "xtask spec"
xtest     = "xtask test"
